let VARIANT_META = {};
let SPRITES = [];
let SPRITE_IMAGES = {};
let SPRITE_VARIANTS = {};
let SEASONS = {};
let EVENTS = {};

const state = {
  collection: {},
  currentDeck: [],
  currentIndex: 0,
  activeDetailId: null,
  userId: null,
  username: null,
  checklistFilter: "all",
  checklistSearch: "",
  checklistSort: "alpha",
  expandedSprite: null,
  squadMembers: [],
  squadFilter: "all",
  squadMemberFilter: "all",
  squadSearch: "",
  squadView: "table",
  activeSquad: null,
  squadCreatedBy: null,
  squadJoinOpen: true,
  compareTarget: null,
  compareToken: null,
  compareMode: "friend"
};

const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => Array.from(document.querySelectorAll(selector));

const els = {
  tabs: $$(".tab"),
  views: $$(".view"),
  ownedCount: $("#ownedCount"),
  totalCount: $("#totalCount"),
  percentCount: $("#percentCount"),
  ring: $(".ring"),
  card: $("#spriteCard"),
  cardAvatar: $("#spriteAvatar"),
  cardRarity: $("#cardRarity"),
  cardName: $("#cardName"),
  cardVariant: $("#cardVariant"),
  cardEffect: $("#cardEffect"),
  cardStatus: $("#cardStatus"),
  cardIndex: $("#cardIndex"),
  cardProgress: $("#cardProgress"),
  cardProgressText: $("#cardProgressText"),
  cardProgressFill: $("#cardProgressFill"),
  swipeBadge: $("#swipeBadge"),
  deckFilter: $("#deckFilter"),
  shuffleDeck: $("#shuffleDeck"),
  checklistList: $("#checklistList"),
  filterChipsBar: $("#filterChipsBar"),
  checklistSort: $("#checklistSort"),
  missingList: $("#missingList"),
  searchInput: $("#searchInput"),
  exportData: $("#exportData"),
  importData: $("#importData"),
  resetData: $("#resetData"),
  copyMissing: $("#copyMissing"),
  themeToggle: $("#themeToggle"),
  toast: $("#toast"),
  statsRingCircle: $("#statsRingCircle"),
  statsHeroPct: $("#statsHeroPct"),
  statsHeroDetail: $("#statsHeroDetail"),
  kpiSprites: $("#kpiSprites"),
  kpiVariants: $("#kpiVariants"),
  kpiPriorities: $("#kpiPriorities"),
  rarityBars: $("#rarityBars"),
  variantBars: $("#variantBars"),
  statsInsights: $("#statsInsights"),
  communityStats: $("#communityStats"),
  squadLobby: $("#squadLobby"),
  squadActive: $("#squadActive"),
  squadNameInput: $("#squadNameInput"),
  squadCodeInput: $("#squadCodeInput"),
  squadCreateBtn: $("#squadCreateBtn"),
  squadJoinBtn: $("#squadJoinBtn"),
  squadActiveName: $("#squadActiveName"),
  squadActiveCode: $("#squadActiveCode"),
  squadCopyCode: $("#squadCopyCode"),
  squadShareBtn: $("#squadShareBtn"),
  squadLeaveBtn: $("#squadLeaveBtn"),
  squadRefreshBtn: $("#squadRefreshBtn"),
  squadSearchInput: $("#squadSearchInput"),
  squadDuelBar: $("#squadDuelBar"),
  duelPlayerA: $("#duelPlayerA"),
  duelPlayerB: $("#duelPlayerB"),
  squadCounter: $("#squadCounter"),
  squadMembers: $("#squadMembers"),
  squadMemberFilter: $("#squadMemberFilter"),
  squadMemberSummary: $("#squadMemberSummary"),
  squadRecommendedFriends: $("#squadRecommendedFriends"),
  squadComplementaryPairs: $("#squadComplementaryPairs"),
  squadFilter: $("#squadFilter"),
  squadTableWrap: $("#squadTableWrap"),
  memberActionsDialog: $("#memberActionsDialog"),
  memberActionsTitle: $("#memberActionsTitle"),
  memberActionsList: $("#memberActionsList"),
  memberActionsClose: $("#memberActionsClose"),
  spriteDetailDialog: $("#spriteDetailDialog"),
  spriteDetailContent: $("#spriteDetailContent"),
  dialog: $("#detailDialog"),
  dialogAvatar: $("#dialogAvatar"),
  dialogRarity: $("#dialogRarity"),
  dialogTitle: $("#dialogTitle"),
  dialogVariant: $("#dialogVariant"),
  dialogEffect: $("#dialogEffect"),
  dialogNote: $("#dialogNote"),
  compareForm: $("#compareForm"),
  compareTokenInput: $("#compareTokenInput"),
  compareLoadBtn: $("#compareLoadBtn"),
  compareShareBtn: $("#compareShareBtn"),
  compareStatus: $("#compareStatus"),
  compareResults: $("#compareResults"),
  compareSummary: $("#compareSummary"),
  compareSquads: $("#compareSquads"),
  compareLists: $("#compareLists"),
  compareTable: $("#compareTable"),
  compareRecommendations: $("#compareRecommendations"),
  compareActions: $("#compareActions"),
  comparePlayerAName: $("#comparePlayerAName"),
  comparePlayerBName: $("#comparePlayerBName"),
  compareSpriteDetailContent: $("#compareSpriteDetailContent"),
  shareCompareDialog: $("#shareCompareDialog"),
  shareCompareTitle: $("#shareCompareTitle"),
  shareCompareIntro: $("#shareCompareIntro"),
  shareCompareOptions: $("#shareCompareOptions"),
  shareCompareDuration: $("#shareCompareDuration"),
  shareCompareCollection: $("#shareCompareCollection"),
  shareCompareNotes: $("#shareCompareNotes"),
  shareComparePriorities: $("#shareComparePriorities"),
  shareCompareVisitor: $("#shareCompareVisitor"),
  shareCompareGenerate: $("#shareCompareGenerate"),
  shareCompareResult: $("#shareCompareResult"),
  shareCompareQr: $("#shareCompareQr"),
  shareCompareUrl: $("#shareCompareUrl"),
  shareCompareCopy: $("#shareCompareCopy"),
  squadInviteDialog: $("#squadInviteDialog"),
  squadInviteDialogTitle: $("#squadInviteDialogTitle"),
  squadInviteDialogOptions: $("#squadInviteDialogOptions"),
  squadInviteDialogConfirm: $("#squadInviteDialogConfirm")
};
