let VARIANT_META = {};
let SPRITES = [];
let SPRITE_IMAGES = Object.create(null);
let SPRITE_VARIANTS = Object.create(null);
let SEASONS = Object.create(null);
let EVENTS = Object.create(null);

const state = {
  collection: Object.create(null),
  currentDeck: [],
  currentIndex: 0,
  swipeSession: {
    active: false,
    paused: false,
    total: 0,
    processed: 0,
    actions: [],
    counts: Object.create(null),
    startedAt: null
  },
  activeDetailId: null,
  userId: null,
  username: null,
  checklistFilter: "all",
  checklistSearch: "",
  checklistSort: "alpha",
  commandSeasonId: null,
  passportMissingVariantIds: null,
  expandedSprite: null,
  squadMembers: [],
  squadFilter: "all",
  squadMemberFilter: "all",
  squadSearch: "",
  squadView: "table",
  activeSquad: null,
  squadCreatedBy: null,
  squadJoinOpen: true,
  compareTarget: null,
  compareToken: null,
  compareMode: "friend",
  // Étape 48 — contextual notification destinations
  compareFocusVariantIds: null,
  missingEventFilter: null,
  // Farm list controls are intentionally view-local: they must not alter the
  // checklist filters or the collection data itself.
  missingSearch: "",
  missingFilter: "all",
  missingSort: "priority",
  missingCollapsedSections: Object.create(null),
  farmPlan: null,
  // Hidden collection views are refreshed lazily after a swipe. Rebuilding
  // their long lists while the deck is animating caused avoidable mobile jank.
  collectionViewDirty: {
    checklist: false,
    missing: false,
    stats: false
  },
  homeViewDirty: false
};

const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => Array.from(document.querySelectorAll(selector));

const els = {
  tabs: $$(".tab"),
  views: $$(".view"),
  ownedCount: $("#ownedCount"),
  totalCount: $("#totalCount"),
  percentCount: $("#percentCount"),
  ring: $(".ring"),
  card: $("#spriteCard"),
  cardAvatar: $("#spriteAvatar"),
  cardRarity: $("#cardRarity"),
  cardName: $("#cardName"),
  cardVariant: $("#cardVariant"),
  cardEffect: $("#cardEffect"),
  cardStatus: $("#cardStatus"),
  cardIndex: $("#cardIndex"),
  cardProgress: $("#cardProgress"),
  cardProgressText: $("#cardProgressText"),
  cardProgressFill: $("#cardProgressFill"),
  cardMastery: $("#cardMastery"),
  cardMasteryLabel: $("#cardMasteryLabel"),
  cardMasteryLevels: $("#cardMasteryLevels"),
  swipeBadge: $("#swipeBadge"),
  deckFilter: $("#deckFilter"),
  shuffleDeck: $("#shuffleDeck"),
  checklistList: $("#checklistList"),
  filterChipsBar: $("#filterChipsBar"),
  checklistSort: $("#checklistSort"),
  missingList: $("#missingList"),
  searchInput: $("#searchInput"),
  exportData: $("#exportData"),
  importData: $("#importData"),
  resetData: $("#resetData"),
  copyMissing: $("#copyMissing"),
  themeToggle: $("#themeToggle"),
  toast: $("#toast"),
  statsRingCircle: $("#statsRingCircle"),
  statsHeroPct: $("#statsHeroPct"),
  statsHeroDetail: $("#statsHeroDetail"),
  statsHeroSupport: $("#statsHeroSupport"),
  statsHeroRemaining: $("#statsHeroRemaining"),
  kpiSprites: $("#kpiSprites"),
  kpiSpritesHint: $("#kpiSpritesHint"),
  kpiVariants: $("#kpiVariants"),
  kpiVariantsHint: $("#kpiVariantsHint"),
  kpiPriorities: $("#kpiPriorities"),
  kpiPrioritiesHint: $("#kpiPrioritiesHint"),
  rarityBars: $("#rarityBars"),
  variantBars: $("#variantBars"),
  statsInsights: $("#statsInsights"),
  communityStats: $("#communityStats"),
  squadLobby: $("#squadLobby"),
  squadActive: $("#squadActive"),
  squadNameInput: $("#squadNameInput"),
  squadCodeInput: $("#squadCodeInput"),
  squadCreateBtn: $("#squadCreateBtn"),
  squadJoinBtn: $("#squadJoinBtn"),
  squadActiveName: $("#squadActiveName"),
  squadActiveCode: $("#squadActiveCode"),
  squadCopyCode: $("#squadCopyCode"),
  squadShareBtn: $("#squadShareBtn"),
  squadLeaveBtn: $("#squadLeaveBtn"),
  squadRefreshBtn: $("#squadRefreshBtn"),
  squadSearchInput: $("#squadSearchInput"),
  squadDuelBar: $("#squadDuelBar"),
  duelPlayerA: $("#duelPlayerA"),
  duelPlayerB: $("#duelPlayerB"),
  squadCounter: $("#squadCounter"),
  squadMembers: $("#squadMembers"),
  squadMemberFilter: $("#squadMemberFilter"),
  squadMemberSummary: $("#squadMemberSummary"),
  squadRecommendedFriends: $("#squadRecommendedFriends"),
  squadComplementaryPairs: $("#squadComplementaryPairs"),
  squadFilter: $("#squadFilter"),
  squadTableWrap: $("#squadTableWrap"),
  squadEngine: $("#squadEngine"),
  squadEngineBtn: $("#squadEngineBtn"),
  squadEngineCloseBtn: $("#squadEngineCloseBtn"),
  squadEngineVersion: $("#squadEngineVersion"),
  memberActionsDialog: $("#memberActionsDialog"),
  memberActionsTitle: $("#memberActionsTitle"),
  memberActionsList: $("#memberActionsList"),
  memberActionsClose: $("#memberActionsClose"),
  spriteDetailDialog: $("#spriteDetailDialog"),
  spriteDetailContent: $("#spriteDetailContent"),
  dialog: $("#detailDialog"),
  dialogAvatar: $("#dialogAvatar"),
  dialogRarity: $("#dialogRarity"),
  dialogTitle: $("#dialogTitle"),
  dialogVariant: $("#dialogVariant"),
  dialogEffect: $("#dialogEffect"),
  dialogNote: $("#dialogNote"),
  compareForm: $("#compareForm"),
  compareTokenInput: $("#compareTokenInput"),
  compareLoadBtn: $("#compareLoadBtn"),
  compareShareBtn: $("#compareShareBtn"),
  compareStatus: $("#compareStatus"),
  compareResults: $("#compareResults"),
  compareSummary: $("#compareSummary"),
  compareSquads: $("#compareSquads"),
  compareLists: $("#compareLists"),
  compareTable: $("#compareTable"),
  compareRecommendations: $("#compareRecommendations"),
  compareActions: $("#compareActions"),
  comparePlayerAName: $("#comparePlayerAName"),
  comparePlayerBName: $("#comparePlayerBName"),
  compareSpriteDetailContent: $("#compareSpriteDetailContent"),
  shareCompareDialog: $("#shareCompareDialog"),
  shareCompareTitle: $("#shareCompareTitle"),
  shareCompareIntro: $("#shareCompareIntro"),
  shareCompareOptions: $("#shareCompareOptions"),
  shareCompareDuration: $("#shareCompareDuration"),
  shareCompareCollection: $("#shareCompareCollection"),
  shareCompareNotes: $("#shareCompareNotes"),
  shareComparePriorities: $("#shareComparePriorities"),
  shareCompareVisitor: $("#shareCompareVisitor"),
  shareCompareGenerate: $("#shareCompareGenerate"),
  shareCompareResult: $("#shareCompareResult"),
  shareCompareQr: $("#shareCompareQr"),
  shareCompareUrl: $("#shareCompareUrl"),
  shareCompareCopy: $("#shareCompareCopy"),
  squadInviteDialog: $("#squadInviteDialog"),
  squadInviteDialogTitle: $("#squadInviteDialogTitle"),
  squadInviteDialogOptions: $("#squadInviteDialogOptions"),
  squadInviteDialogConfirm: $("#squadInviteDialogConfirm")
};
